apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oxsp-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-owwu@sha256:124ba2bae3e0f2d3684af05476105946225e51906f7dbc9e7b20c0786eabc11e
        name: my-go
        resources: {}
status: {}
