apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
    app.kubernetes.io/part-of: mc-golang-nested
  name: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-owwu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oxsp-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-owwu@sha256:124ba2bae3e0f2d3684af05476105946225e51906f7dbc9e7b20c0786eabc11e
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
