apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-co4a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-co4a
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-co4a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-co4a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-co4a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oxsp-tenant/mc-golang-nested/componentb-devfile-sample-go-basic-private-devfile-nested-co4a@sha256:b59e2f667110790dfbeb58de574e095e7e77b3a6cb879453f0ad0ba39c5dfbd8
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
